ty:
  view-mapping:
    #前台
    "[/rs/que-bank]": "rs/que-bank"
    #后台管理
    "[/adm/index]": "adm/rs/book"
    "[/adm/rs/book/view]": "adm/rs/book"
    "[/adm/rs/knowledge/view]": "adm/rs/knowledge"
    "[/adm/bbd/student/view]": "adm/bbd/student"